# copy to config.yaml
discord_bot_token: '...'

# channel id where the bot will listen for commands
bot_channel_id: 000

# list of regex to match team channels to move from
from_channels: ['[Bb]lood [Ee]agle', '[Dd]iamond [Ss]word', '[Bb][Ee]', '[Dd][Ss]']

# channel that users will be moved to
to_channel_id: 000
